# Generated by Django 3.2.4 on 2021-06-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestskill',
            options={'verbose_name': 'RequestSkill', 'verbose_name_plural': 'RequestSkill'},
        ),
        migrations.AlterField(
            model_name='requestskill',
            name='preset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.preset', verbose_name='preset'),
        ),
    ]
