# Generated by Django 3.2.4 on 2021-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='competency',
            field=models.CharField(choices=[('Python', 'Python'), ('java', 'java'), ('JavaScript', 'JavaScript'), ('Databases', 'Databases')], max_length=200),
        ),
    ]
