# Generated by Django 3.2.4 on 2021-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_competency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='competency',
            field=models.CharField(choices=[('Python', 'Python'), ('java', 'java')], max_length=200),
        ),
    ]
