# Generated by Django 3.2.4 on 2021-06-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniority_level', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='employee')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'EmployeeSkill',
                'verbose_name_plural': 'EmployeeSkills',
            },
        ),
    ]
