# Generated by Django 3.2.4 on 2021-06-23 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskill',
            name='seniority_level',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
